export declare const PRODUCT_CREATED="Product created!"   
export declare const PRODUCT_UPDATED="Product updated!"
export declare const PRODUCT_DELETED="Product deleted!"
export declare const PRODUCT_LISTED="Products Listed!"
export declare const PRODUCT_LISTED_BY_ID="Product Listed!"
export declare const PRODUCT_NOT_FOUND="Product not found!"
export declare const USER_NOT_FOUND = "User not found!"
export declare const USER_LOGIN_SUCCESS="Login is success!"   
export declare const USER_GET_LIST = "User listed!" 
export declare const USER_REGISTER_SUCCESS = "Register is success"  
export declare const USER_NOT_AUTH = "User not authenticated!"   
export declare const USER_ALREADY_EXIST="User not exist!"

